Repository jfrog/jfrog-azure-devops-extension, pull requests merged in 2023-03, with the labels that each got.

#382 Update JFrog-CLI to v2.34.6
  jfrog-tasks-utils/utils.js
Labels: dependencies

#387 Remove demand for "gradle" in the Gradle task
  tasks/JFrogGradle/task.json
Labels: improvement

#390 Fix git commit message quotes
  .jfrog-pipelines/pipelines.release.yml
Labels: ignore for release
